#Stage 1
FROM python:3.11 as train
WORKDIR /app
RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    tensorflow==2.14.0 \
    fastapi==0.115.3 \
    uvicorn==0.32.0 \
    librosa==0.10.1 \
    numpy==1.26.4 \
    scipy==1.14.1 \
    pyaudio==0.2.14\
    python-multipart

COPY . .

WORKDIR /app/train_model
RUN python train.py


#Stage 2
FROM python:3.11 as deploy
WORKDIR /app

RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    tensorflow==2.14.0 \
    fastapi==0.115.3 \
    uvicorn==0.32.0 \
    librosa==0.10.1 \
    numpy==1.26.4 \
    scipy==1.14.1 \
    pyaudio==0.2.14\
    python-multipart

COPY --from=train /app/app.py ./
COPY --from=train /app/train_model/*.keras ./

EXPOSE 8125

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8125", "--log-level", "debug"]